### ISSUE TITLE
[Request] New configs entries on sugarcane.yml

### ISSUE THREAD

**Issue by NovaPixell** [SugarcaneMC/Sugarcane#22]
It would be interesting to bring the following configurations from Yatopia:

`itemStuckSleepTicks: 15`

```
    collisions:
      players: true
      animals: false
      ambient: true
      monsters: false
      villagers: true
      pillagers: false
      iron-golems: true
      misc: true
      items: true
      water-creature: false
      water-ambient: false
```

```
    ticks-per:
      full-hopper-cooldown: 128
    pigmen:
      dont-target-unless-hit: true
```

```
  intervals:
    player-time-statistics: 24
```

```
  tick:
    enchanting-tables: false
```
